# Generated by Django 4.1.3 on 2023-01-16 16:57

from django.db import migrations
import storage.fields


class Migration(migrations.Migration):

    dependencies = [
        ("calendrier_avent_2022", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="picture",
            field=storage.fields.ImageField(
                null=True, upload_to="", verbose_name="Photo"
            ),
        ),
    ]
