# Generated by Django 4.1.3 on 2022-12-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendrier_avent_2022", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="enfant",
            new_name="child",
        ),
        migrations.RenameField(
            model_name="day",
            old_name="jour",
            new_name="day",
        ),
        migrations.RenameField(
            model_name="day",
            old_name="photo",
            new_name="picture",
        ),
    ]
