# Generated by Django 4.1.3 on 2022-12-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendrier_avent_2022",
            "0002_rename_enfant_day_child_rename_jour_day_day_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={"verbose_name": "Jour"},
        ),
    ]
