# Generated by Django 4.1.3 on 2022-12-29 16:02

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("calendrier_avent_2022", "0003_alter_day_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="picture",
            field=filer.fields.image.FilerImageField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Photo",
            ),
        ),
    ]
