# Generated by Django 4.2.3 on 2023-09-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="year",
            name="is_active",
            field=models.BooleanField(verbose_name="active year"),
        ),
        migrations.AlterField(
            model_name="year",
            name="start_year",
            field=models.IntegerField(unique=True, verbose_name="start year"),
        ),
    ]
