# Generated by Django 5.1.4 on 2024-12-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_year_is_active_alter_year_start_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(blank=True, verbose_name="content")),
                ("hidden", models.BooleanField(default=False, verbose_name="hidden page")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_pages",
                        to="common.page",
                        verbose_name="Previous page",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "ordering": ["order"],
            },
        ),
    ]
