# Generated by Django 5.1.4 on 2024-12-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="year",
            options={"ordering": ["-start_year"], "verbose_name": "school year", "verbose_name_plural": "school years"},
        ),
    ]
