# Generated by Django 5.2.4 on 2025-07-28 09:04

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_year_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
            ],
            options={
                "verbose_name": "date category",
                "verbose_name_plural": "date categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                ("start_time", models.TimeField(blank=True, null=True, verbose_name="start time")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="end time")),
                ("time_text", common.fields.DatalistField(blank=True, max_length=50, verbose_name="Time (as text)")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("short_name", models.CharField(blank=True, max_length=50, verbose_name="short name")),
                ("place", models.CharField(blank=True, max_length=100, verbose_name="place")),
                ("cancelled", models.BooleanField(verbose_name="cancelled")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dates",
                        related_query_name="date",
                        to="common.datecategory",
                        verbose_name="Categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "date",
                "ordering": ["start_date", "start_time"],
            },
        ),
    ]
