# Generated by Django 5.2.4 on 2025-07-29 10:44

import common.fields
import common.models
import django.db.models.deletion
import django.utils.timezone
import storage.fields
from django.conf import settings
from django.db import migrations, models

from common.migration_helpers import merge


class Migration(migrations.Migration):

    dependencies = [
        ("aumonerie", "0009_child_paye_checkbox"),
        ("common", "0005_datecategory_date"),
        ("espacecate", "0010_child_paye_checkbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(blank=True, verbose_name="content")),
                ("date", models.DateField(default=django.utils.timezone.now, verbose_name="date")),
                ("hidden", models.BooleanField(default=False, verbose_name="hidden article")),
            ],
            options={
                "verbose_name": "article",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True, verbose_name="title")),
            ],
            options={
                "verbose_name": "document category",
                "verbose_name_plural": "document categories",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "group",
            },
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", storage.fields.ImageField(upload_to="", verbose_name="image")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.article", verbose_name="Article"
                    ),
                ),
            ],
            options={
                "verbose_name": "article image",
                "verbose_name_plural": "article images",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=100, verbose_name="Nom de famille")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                ("lieu_naissance", models.CharField(max_length=100, verbose_name="Lieu de naissance")),
                ("adresse", models.TextField(verbose_name="Adresse")),
                ("ecole", models.CharField(max_length=100, verbose_name="École")),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("PS", "Petite section"),
                            ("MS", "Moyenne section"),
                            ("GS", "Grande section"),
                            ("CP", "CP"),
                            ("CE1", "CE1"),
                            ("CE2", "CE2"),
                            ("CM1", "CM1"),
                            ("CM2", "CM2"),
                            ("6eme", "6ème"),
                            ("5eme", "5ème"),
                            ("4eme", "4ème"),
                            ("3eme", "3ème"),
                            ("2nde", "2nde"),
                            ("1ere", "1ère"),
                            ("terminale", "Terminale"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Classe",
                    ),
                ),
                ("bapteme", models.BooleanField(verbose_name="Baptême")),
                ("date_bapteme", models.DateField(blank=True, null=True, verbose_name="Date du Baptême")),
                ("lieu_bapteme", models.CharField(blank=True, max_length=100, verbose_name="Lieu du Baptême")),
                ("premiere_communion", models.BooleanField(verbose_name="Première Communion")),
                (
                    "date_premiere_communion",
                    models.DateField(blank=True, null=True, verbose_name="Date de la Première Communion"),
                ),
                (
                    "lieu_premiere_communion",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu de la Première Communion"),
                ),
                ("profession", models.BooleanField(verbose_name="Profession de foi")),
                (
                    "date_profession",
                    models.DateField(blank=True, null=True, verbose_name="Date de la Profession de Foi"),
                ),
                (
                    "lieu_profession",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu de la Profession de Foi"),
                ),
                ("confirmation", models.BooleanField(verbose_name="Confirmation")),
                ("date_confirmation", models.DateField(blank=True, null=True, verbose_name="Date de la Confirmation")),
                (
                    "lieu_confirmation",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu de la Confirmation"),
                ),
                ("nom_pere", models.CharField(blank=True, max_length=100, verbose_name="Nom et prénom du père")),
                ("adresse_pere", models.TextField(blank=True, verbose_name="Adresse du père")),
                ("tel_pere", models.CharField(blank=True, max_length=10, verbose_name="Téléphone du père")),
                ("email_pere", models.EmailField(blank=True, max_length=100, verbose_name="Email du père")),
                ("nom_mere", models.CharField(blank=True, max_length=100, verbose_name="Nom et prénom de la mère")),
                ("adresse_mere", models.TextField(blank=True, verbose_name="Adresse de la mère")),
                ("tel_mere", models.CharField(blank=True, max_length=10, verbose_name="Téléphone de la mère")),
                ("email_mere", models.EmailField(blank=True, max_length=100, verbose_name="Email de la mère")),
                ("freres_soeurs", models.TextField(blank=True, verbose_name="Frères et soeurs")),
                ("autres_infos", models.TextField(blank=True, verbose_name="Autres informations")),
                ("photos", models.BooleanField(verbose_name="Publication des photos")),
                ("frais", common.fields.PriceField(verbose_name="Participation aux frais")),
                ("communion_cette_annee", models.BooleanField(default=False, verbose_name="Communion cette année")),
                (
                    "profession_cette_annee",
                    models.BooleanField(default=False, verbose_name="Profession de Foi cette année"),
                ),
                (
                    "confirmation_cette_annee",
                    models.BooleanField(default=False, verbose_name="Confirmation cette année"),
                ),
                ("paye", models.BooleanField(default=False, verbose_name="Payé")),
                ("signe", models.BooleanField(default=False, verbose_name="Signé")),
                ("photo", storage.fields.ImageField(blank=True, null=True, upload_to="", verbose_name="Photo")),
                (
                    "date_inscription",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date et heure d'inscription"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        default=common.models.Year.get_current_pk,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.year",
                        verbose_name="School year",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.group",
                        verbose_name="Groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "child",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="document title")),
                ("file", storage.fields.FileField(null=True, upload_to="", verbose_name="file")),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="common.documentcategory", verbose_name="Categories"),
                ),
            ],
            options={
                "verbose_name": "document",
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KT", "Rencontre de caté"),
                            ("EVF", "Rencontre d'éveil à la foi"),
                            ("TF", "Temps fort"),
                            ("MF", "Messe des familles"),
                            ("A_COL", "Rencontre d'aumônerie (collège)"),
                            ("A_LYC", "Rencontre d'aumônerie (lycée)"),
                            ("PF", "Profession de Foi"),
                            ("CONF", "Confirmation"),
                        ],
                        max_length=5,
                        verbose_name="kind",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Replaces the meeting kind", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        default=common.models.get_default_group,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="common.group",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_present", models.BooleanField(verbose_name="present")),
                ("has_warned", models.BooleanField(verbose_name="has warned")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="common.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="common.meeting",
                        verbose_name="Meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance",
            },
        ),
        migrations.RunPython(
            merge(["espacecate", "aumonerie"], "common"),
            merge("common", "espacecate"),
        ),
    ]
