# Generated by Django 5.2.4 on 2025-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_article_documentcategory_group_articleimage_child_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="app",
            field=models.CharField(blank=True, max_length=100, verbose_name="app"),
        ),
    ]
