# Generated by Django 5.2.4 on 2025-07-29 15:05

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_group_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="OldChild",
            fields=[],
            options={
                "verbose_name": "old child",
                "verbose_name_plural": "old children",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.child",),
        ),
        migrations.AlterField(
            model_name="child",
            name="groupe",
            field=models.ForeignKey(
                default=common.models.get_default_group,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.group",
                verbose_name="Groupe",
            ),
        ),
    ]
