# Generated by Django 5.2.4 on 2025-07-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_oldchild_alter_child_groupe"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastChildVersion",
            fields=[],
            options={
                "verbose_name": "last child version",
                "verbose_name_plural": "last child versions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.child",),
        ),
    ]
