# Generated by Django 5.2.4 on 2025-07-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_lastchildversion_group_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="code_postal_ville",
            field=models.CharField(default="-", max_length=100, verbose_name="Code postal et ville"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="child",
            name="code_postal_ville_mere",
            field=models.CharField(blank=True, max_length=100, verbose_name="Code postal et ville de la mère"),
        ),
        migrations.AddField(
            model_name="child",
            name="code_postal_ville_pere",
            field=models.CharField(blank=True, max_length=100, verbose_name="Code postal et ville du père"),
        ),
        migrations.AddField(
            model_name="child",
            name="email_jeune",
            field=models.EmailField(blank=True, max_length=100, verbose_name="Email du jeune"),
        ),
        migrations.AddField(
            model_name="child",
            name="tel_jeune",
            field=models.CharField(blank=True, max_length=10, verbose_name="Téléphone du jeune"),
        ),
    ]
