# Generated by Django 5.2.5 on 2025-08-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "common",
            "0010_child_code_postal_ville_child_code_postal_ville_mere_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.child",
                verbose_name="Child",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.meeting",
                verbose_name="Meeting",
            ),
        ),
    ]
