# Generated by Django 5.2.5 on 2025-08-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_attendance_child_alter_attendance_meeting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="categories",
        ),
        migrations.DeleteModel(
            name="DocumentCategory",
        ),
    ]
