# Generated by Django 5.2.5 on 2025-08-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_remove_document_categories_delete_documentcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
            ],
            options={
                "verbose_name": "document category",
                "verbose_name_plural": "document categories",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="categories",
            field=models.ManyToManyField(blank=True, to="common.documentcategory", verbose_name="Categories"),
        ),
    ]
