# Generated by Django 5.2.5 on 2025-08-26 12:02

import django.db.models.deletion
import storage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_alter_attendance_child_alter_attendance_meeting"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    storage.fields.ImageField(upload_to="", verbose_name="image"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.page",
                        verbose_name="Page",
                    ),
                ),
            ],
            options={
                "verbose_name": "page image",
                "verbose_name_plural": "page images",
            },
        ),
    ]
