# Generated by Django 5.2.6 on 2025-09-21 14:36

from django.db import migrations, models

from common.migration_helpers import migrate_pages_backwards, migrate_pages_forwards


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_pageimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="url",
            field=models.CharField(blank=True, max_length=255, verbose_name="URL"),
        ),
        migrations.RunPython(migrate_pages_forwards, migrate_pages_backwards),
    ]
