# Generated by Django 5.2.6 on 2025-09-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="parent_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_pages",
                to="common.page",
                verbose_name="Previous page",
            ),
        ),
    ]
