# Generated by Django 5.2.5 on 2025-08-12 12:45

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_alter_page_parent_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="tel_jeune",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Téléphone du jeune",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="tel_mere",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Téléphone de la mère",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="tel_pere",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Téléphone du père",
            ),
        ),
    ]
