# Generated by Django 5.2.6 on 2026-02-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_alter_phone_number_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "site message",
                "verbose_name_plural": "site messages",
                "ordering": ("-created_at",),
            },
        ),
    ]
