# Generated by Django 5.2.6 on 2026-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_alter_phone_number_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["-date"], "verbose_name": "meeting"},
        ),
        migrations.AddField(
            model_name="date",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AddField(
            model_name="date",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
    ]
