# Generated by Django 5.2.6 on 2026-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_sitemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitemessage",
            name="level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "DEBUG"),
                    ("INFO", "INFO"),
                    ("SUCCESS", "SUCCESS"),
                    ("WARNING", "WARNING"),
                    ("ERROR", "ERROR"),
                ],
                default="INFO",
                max_length=10,
                verbose_name="level",
            ),
        ),
    ]
