# Generated by Django 4.2.3 on 2023-09-30 07:21

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storage.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(blank=True, verbose_name="content")),
                ("date", models.DateField(default=django.utils.timezone.now, verbose_name="date")),
                ("hidden", models.BooleanField(default=False, verbose_name="hidden article")),
            ],
            options={
                "verbose_name": "article",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                ("start_time", models.TimeField(blank=True, null=True, verbose_name="start time")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="end time")),
                ("time_text", common.fields.DatalistField(blank=True, max_length=50, verbose_name="Time (as text)")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("short_name", models.CharField(blank=True, max_length=50, verbose_name="short name")),
                ("place", models.CharField(blank=True, max_length=100, verbose_name="place")),
                ("cancelled", models.BooleanField(verbose_name="cancelled")),
            ],
            options={
                "verbose_name": "date",
                "ordering": ["start_date", "start_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True, verbose_name="title")),
            ],
            options={
                "verbose_name": "document category",
                "verbose_name_plural": "document categories",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "group",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="date")),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Replaces the meeting kind", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A_COL", "Rencontre d'aumônerie (collège)"),
                            ("A_LYC", "Rencontre d'aumônerie (lycée)"),
                            ("MF", "Messe des familles"),
                            ("PF", "Profession de Foi"),
                            ("CONF", "Confirmation"),
                        ],
                        max_length=5,
                        verbose_name="kind",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting",
                "ordering": ["date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(blank=True, verbose_name="content")),
                ("hidden", models.BooleanField(default=False, verbose_name="hidden page")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aumonerie.page",
                        verbose_name="Previous page",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", storage.fields.ImageField(upload_to="", verbose_name="image")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aumonerie.page", verbose_name="Page"
                    ),
                ),
            ],
            options={
                "verbose_name": "page image",
                "verbose_name_plural": "page images",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="document title")),
                ("file", storage.fields.FileField(null=True, upload_to="", verbose_name="file")),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="aumonerie.documentcategory", verbose_name="Categories"),
                ),
            ],
            options={
                "verbose_name": "document",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=100, verbose_name="Nom de famille")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                ("lieu_naissance", models.CharField(max_length=100, verbose_name="Lieu de naissance")),
                ("adresse", models.TextField(verbose_name="Adresse")),
                (
                    "paye",
                    models.CharField(
                        choices=[("non", "Non"), ("attente", "En attente"), ("oui", "Oui")],
                        default="non",
                        max_length=10,
                        verbose_name="Payé",
                    ),
                ),
                ("signe", models.BooleanField(default=False, verbose_name="Signé")),
                ("photo", storage.fields.ImageField(blank=True, null=True, upload_to="", verbose_name="Photo")),
                (
                    "date_inscription",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date et heure d'inscription"),
                ),
                ("ecole", models.CharField(max_length=100, verbose_name="École")),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("6e", "6ème"),
                            ("5e", "5ème"),
                            ("4e", "4ème"),
                            ("3e", "3ème"),
                            ("2nde", "2nde"),
                            ("1ere", "1ère"),
                            ("terminale", "Terminale"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Classe",
                    ),
                ),
                ("bapteme", models.BooleanField(verbose_name="Baptême")),
                ("date_bapteme", models.DateField(blank=True, null=True, verbose_name="Date du Baptême")),
                ("lieu_bapteme", models.CharField(blank=True, max_length=100, verbose_name="Lieu du Baptême")),
                ("premiere_communion", models.BooleanField(verbose_name="Première Communion")),
                (
                    "date_premiere_communion",
                    models.DateField(blank=True, null=True, verbose_name="Date de la Première Communion"),
                ),
                (
                    "lieu_premiere_communion",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu de la Première Communion"),
                ),
                ("profession", models.BooleanField(verbose_name="Profession de foi")),
                (
                    "date_profession",
                    models.DateField(blank=True, null=True, verbose_name="Date de la Profession de Foi"),
                ),
                (
                    "lieu_profession",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu de la Profession de Foi"),
                ),
                ("confirmation", models.BooleanField(verbose_name="Confirmation")),
                ("date_confirmation", models.DateField(blank=True, null=True, verbose_name="Date de la Confirmation")),
                (
                    "lieu_confirmation",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu de la Confirmation"),
                ),
                ("nom_pere", models.CharField(blank=True, max_length=100, verbose_name="Nom et prénom du père")),
                ("adresse_pere", models.TextField(blank=True, verbose_name="Adresse du père")),
                ("tel_pere", models.CharField(blank=True, max_length=10, verbose_name="Téléphone du père")),
                ("email_pere", models.EmailField(blank=True, max_length=100, verbose_name="Email du père")),
                ("nom_mere", models.CharField(blank=True, max_length=100, verbose_name="Nom et prénom de la mère")),
                ("adresse_mere", models.TextField(blank=True, verbose_name="Adresse de la mère")),
                ("tel_mere", models.CharField(blank=True, max_length=10, verbose_name="Téléphone de la mère")),
                ("email_mere", models.EmailField(blank=True, max_length=100, verbose_name="Email de la mère")),
                ("freres_soeurs", models.TextField(blank=True, verbose_name="Frères et soeurs")),
                ("autres_infos", models.TextField(blank=True, verbose_name="Autres informations")),
                ("photos", models.BooleanField(verbose_name="Publication des photos")),
                ("frais", common.fields.PriceField(verbose_name="Participation aux frais")),
                ("profession_cette_annee", models.BooleanField(verbose_name="Profession de Foi cette année")),
                ("confirmation_cette_annee", models.BooleanField(verbose_name="Confirmation cette année")),
                (
                    "groupe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aumonerie.group",
                        verbose_name="Groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "child",
                "ordering": ["nom", "prenom"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_present", models.BooleanField(verbose_name="present")),
                ("has_warned", models.BooleanField(verbose_name="has warned")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        related_query_name="attendance",
                        to="aumonerie.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        related_query_name="attendance",
                        to="aumonerie.meeting",
                        verbose_name="Meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", storage.fields.ImageField(upload_to="", verbose_name="image")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aumonerie.article", verbose_name="Article"
                    ),
                ),
            ],
            options={
                "verbose_name": "article image",
                "verbose_name_plural": "article images",
                "abstract": False,
            },
        ),
    ]
