# Generated by Django 5.1.4 on 2024-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aumonerie", "0003_remove_page_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="confirmation_cette_annee",
            field=models.BooleanField(default=False, verbose_name="Confirmation cette année"),
        ),
        migrations.AlterField(
            model_name="child",
            name="profession_cette_annee",
            field=models.BooleanField(default=False, verbose_name="Profession de Foi cette année"),
        ),
    ]
