# Generated by Django 5.1.4 on 2024-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aumonerie", "0004_add_default_false"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="classe",
            field=models.TextField(
                choices=[
                    ("6eme", "6ème"),
                    ("5eme", "5ème"),
                    ("4eme", "4ème"),
                    ("3eme", "3ème"),
                    ("2nde", "2nde"),
                    ("1ere", "1ère"),
                    ("terminale", "Terminale"),
                    ("autre", "Autre"),
                ],
                max_length=10,
                verbose_name="Classe",
            ),
        ),
    ]
