# Generated by Django 5.1.4 on 2024-12-11 16:15

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aumonerie", "0005_alter_child_classe"),
        ("common", "0004_alter_year_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="year",
            field=models.ForeignKey(
                default=common.models.Year.get_current_pk,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="common.year",
                verbose_name="School year",
            ),
        ),
    ]
