# Generated by Django 5.2.4 on 2025-07-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aumonerie", "0006_child_user_child_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="OldChild",
            fields=[],
            options={
                "verbose_name": "old child",
                "verbose_name_plural": "old children",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("aumonerie.child",),
        ),
    ]
