# Generated by Django 5.2.4 on 2025-07-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aumonerie", "0009_child_paye_checkbox"),
        ("common", "0006_article_documentcategory_group_articleimage_child_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleimage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="child",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="child",
            name="groupe",
        ),
        migrations.RemoveField(
            model_name="child",
            name="user",
        ),
        migrations.RemoveField(
            model_name="child",
            name="year",
        ),
        migrations.RemoveField(
            model_name="document",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="ArticleImage",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Meeting",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Child",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="DocumentCategory",
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.attendance",),
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.meeting",),
        ),
        migrations.CreateModel(
            name="Child",
            fields=[],
            options={
                "verbose_name": "child",
                "verbose_name_plural": "children",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.child",),
        ),
    ]
