# Generated by Django 5.2.6 on 2025-10-17 13:17

import django.db.models.deletion
import storage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("espacecate", "0012_alter_child_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(unique=True, verbose_name="jour")),
                (
                    "saint_name",
                    models.CharField(max_length=100, verbose_name="nom du saint"),
                ),
                ("content", models.TextField(blank=True, verbose_name="contenu")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="espacecate.child",
                        verbose_name="enfant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jour",
            },
        ),
        migrations.CreateModel(
            name="DayImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    storage.fields.ImageField(upload_to="", verbose_name="image"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendrier_avent_2025.day",
                        verbose_name="Day",
                    ),
                ),
            ],
            options={
                "verbose_name": "day image",
                "verbose_name_plural": "day images",
            },
        ),
    ]
