# Generated by Django 5.2.6 on 2025-11-12 18:09

import storage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendrier_avent_2025", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="attributes",
            field=models.TextField(blank=True, verbose_name="attributs"),
        ),
        migrations.AddField(
            model_name="day",
            name="drawing_picture",
            field=storage.fields.ImageField(
                blank=True, null=True, upload_to="", verbose_name="photo du dessin"
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="feast",
            field=models.CharField(blank=True, max_length=100, verbose_name="fête"),
        ),
        migrations.AddField(
            model_name="day",
            name="saint_picture",
            field=storage.fields.ImageField(
                blank=True, null=True, upload_to="", verbose_name="photo du saint"
            ),
        ),
    ]
