# Generated by Django 5.2.6 on 2025-11-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendrier_avent_2025",
            "0002_day_attributes_day_drawing_picture_day_feast_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="attributes",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="attributs"
            ),
        ),
    ]
