# Generated by Django 5.2.6 on 2025-11-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendrier_avent_2025", "0003_alter_day_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ["day"], "verbose_name": "Jour"},
        ),
    ]
