# Generated by Django 4.2.6 on 2023-11-02 13:07

from django.db import migrations, models
import django.db.models.deletion
import storage.fields


class Migration(migrations.Migration):
    dependencies = [
        ("calendrier_avent_2023", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", storage.fields.ImageField(upload_to="", verbose_name="image")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="calendrier_avent_2023.day", verbose_name="Day"
                    ),
                ),
            ],
            options={
                "verbose_name": "day image",
                "verbose_name_plural": "day images",
            },
        ),
    ]
