# Generated by Django 4.2 on 2023-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aumonerie", "0006_child_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name": "child"},
        ),
        migrations.AlterField(
            model_name="child",
            name="date_bapteme",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date du Baptême"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="date_confirmation",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de la Confirmation"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="date_premiere_communion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de la Première Communion"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="date_profession",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de la Profession de Foi"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="frais",
            field=models.PositiveIntegerField(verbose_name="Participation aux frais"),
        ),
        migrations.AlterField(
            model_name="child",
            name="lieu_bapteme",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Lieu du Baptême"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="lieu_confirmation",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Lieu de la Confirmation"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="lieu_premiere_communion",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Lieu de la Première Communion"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="lieu_profession",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Lieu de la Profession de Foi"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="premiere_communion",
            field=models.BooleanField(verbose_name="Première Communion"),
        ),
    ]
