# Generated by Django 4.2 on 2023-07-04 16:25

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ("aumonerie", "0009_child_confirmation_cette_annee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        upload_to="", verbose_name="Image"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aumonerie.page",
                        verbose_name="Page",
                    ),
                ),
            ],
            options={
                "verbose_name": "page image",
                "verbose_name_plural": "page images",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        upload_to="", verbose_name="Image"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aumonerie.article",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "article image",
                "verbose_name_plural": "article images",
                "abstract": False,
            },
        ),
    ]
