# Generated by Django 4.2.3 on 2023-07-23 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aumonerie", "0014_fix_child_ordering"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserVisit",
        ),
    ]
