# Generated by Django 4.2 on 2023-06-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aumonerie", "0015_delete_uservisit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Name"),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A_COL", "Rencontre d'aumônerie (collège)"),
                            ("A_LYC", "Rencontre d'aumônerie (lycée)"),
                            ("MF", "Messe des familles"),
                            ("PF", "Profession de Foi"),
                            ("CONF", "Confirmation"),
                        ],
                        max_length=5,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "date_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aumonerie.date",
                        verbose_name="Date item",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_present", models.BooleanField(verbose_name="Present")),
                ("has_warned", models.BooleanField(verbose_name="Has warned")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aumonerie.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aumonerie.meeting",
                        verbose_name="Meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance",
                "abstract": False,
            },
        ),
    ]
