# Generated by Django 4.2.4 on 2023-08-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aumonerie", "0016_meeting_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="ecole",
            field=models.CharField(max_length=100, verbose_name="École"),
        ),
    ]
