# Generated by Django 4.2.3 on 2023-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aumonerie", "0018_alter_date_options_alter_child_signe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="classe",
            field=models.CharField(
                choices=[
                    ("6e", "6ème"),
                    ("5e", "5ème"),
                    ("4e", "4ème"),
                    ("3e", "3ème"),
                    ("2nde", "2nde"),
                    ("1ere", "1ère"),
                    ("terminale", "Terminale"),
                    ("AUTRE", "Autre"),
                ],
                max_length=10,
                verbose_name="Classe",
            ),
        ),
    ]
