# Generated by Django 4.2.3 on 2023-09-25 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aumonerie", "0023_alter_meeting_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["date"], "verbose_name": "meeting"},
        ),
    ]
