# Generated by Django 4.2.3 on 2023-09-30 06:40

from django.db import migrations, models
import storage.fields


class Migration(migrations.Migration):
    dependencies = [
        ("aumonerie", "0026_alter_attendance_child_alter_attendance_meeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=storage.fields.ImageField(upload_to="", verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="has_warned",
            field=models.BooleanField(verbose_name="has warned"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="is_present",
            field=models.BooleanField(verbose_name="present"),
        ),
        migrations.AlterField(
            model_name="date",
            name="cancelled",
            field=models.BooleanField(verbose_name="cancelled"),
        ),
        migrations.AlterField(
            model_name="date",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="date",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="date",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="date",
            name="place",
            field=models.CharField(blank=True, max_length=100, verbose_name="place"),
        ),
        migrations.AlterField(
            model_name="date",
            name="short_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="short name"),
        ),
        migrations.AlterField(
            model_name="date",
            name="start_date",
            field=models.DateField(verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="date",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="start time"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=storage.fields.FileField(null=True, upload_to="", verbose_name="file"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=100, verbose_name="document title"),
        ),
        migrations.AlterField(
            model_name="documentcategory",
            name="title",
            field=models.CharField(max_length=100, unique=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_COL", "Rencontre d'aumônerie (collège)"),
                    ("A_LYC", "Rencontre d'aumônerie (lycée)"),
                    ("MF", "Messe des familles"),
                    ("PF", "Profession de Foi"),
                    ("CONF", "Confirmation"),
                ],
                max_length=5,
                verbose_name="kind",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="name",
            field=models.CharField(
                blank=True, help_text="Replaces the meeting kind", max_length=100, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="pageimage",
            name="image",
            field=storage.fields.ImageField(upload_to="", verbose_name="image"),
        ),
    ]
