# Generated by Django 4.2 on 2023-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0002_add_documentcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="date",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="End time"),
        ),
        migrations.AlterField(
            model_name="date",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time"),
        ),
    ]
