# Generated by Django 4.2.11 on 2024-11-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0002_alter_page_parent_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=100, verbose_name="Nom de famille")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="", verbose_name="Photo")),
            ],
            options={"verbose_name": "animateur"},
        ),
    ]
