# Generated by Django 4.2 on 2023-06-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0003_fix_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="adresse_mere",
            field=models.TextField(blank=True, verbose_name="Adresse de la mère"),
        ),
        migrations.AlterField(
            model_name="child",
            name="adresse_pere",
            field=models.TextField(blank=True, verbose_name="Adresse du père"),
        ),
        migrations.AlterField(
            model_name="child",
            name="email_mere",
            field=models.EmailField(
                blank=True, max_length=100, verbose_name="Email de la mère"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="email_pere",
            field=models.EmailField(
                blank=True, max_length=100, verbose_name="Email du père"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="freres_soeurs",
            field=models.TextField(blank=True, verbose_name="Frères et soeurs"),
        ),
        migrations.AlterField(
            model_name="child",
            name="tel_mere",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Téléphone de la mère"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="tel_pere",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Téléphone du père"
            ),
        ),
    ]
