# Generated by Django 4.2 on 2023-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0004_alter_family_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentcategory",
            name="title",
            field=models.CharField(max_length=100, unique=True, verbose_name="Title"),
        ),
    ]
