# Generated by Django 4.1.3 on 2022-12-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0005_child"),
    ]

    operations = [
        migrations.RenameField(
            model_name="child",
            old_name="address",
            new_name="adresse",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="level",
            new_name="classe",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="date_of_birth",
            new_name="date_naissance",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="school",
            new_name="ecole",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="place_of_birth",
            new_name="lieu_naissance",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="last_name",
            new_name="nom",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="first_name",
            new_name="prenom",
        ),
        migrations.AlterField(
            model_name="child",
            name="tel_mere",
            field=models.CharField(max_length=10, verbose_name="Téléphone de la mère"),
        ),
        migrations.AlterField(
            model_name="child",
            name="tel_pere",
            field=models.CharField(max_length=10, verbose_name="Téléphone du père"),
        ),
    ]
