# Generated by Django 4.2 on 2023-06-16 15:39

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0006_group_child_paye_child_signe_child_groupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="photo",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                null=True, upload_to="", verbose_name="Photo"
            ),
        ),
    ]
