# Generated by Django 4.2 on 2023-06-17 09:27

import django.core.validators
from django.db import migrations, models
import espacecate.models


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0007_child_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name": "child"},
        ),
        migrations.AlterField(
            model_name="child",
            name="annee_pardon",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        espacecate.models.get_current_year
                    )
                ],
                verbose_name="Année du Sacrement du Pardon",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="date_bapteme",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date du Baptême"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="date_premiere_communion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de la Première Communion"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="frais",
            field=models.PositiveIntegerField(verbose_name="Participation aux frais"),
        ),
        migrations.AlterField(
            model_name="child",
            name="lieu_bapteme",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Lieu du Baptême"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="lieu_premiere_communion",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lieu de la Première Communion",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="premiere_communion",
            field=models.BooleanField(verbose_name="Première Communion"),
        ),
    ]
