# Generated by Django 4.1.3 on 2022-12-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0007_rename_years_evf_child_annees_evf_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Child",
            new_name="Enfant",
        ),
    ]
