# Generated by Django 4.1.3 on 2022-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0011_document_alter_page_order_alter_page_parent_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="media/docs/", verbose_name="Document"),
        ),
    ]
