# Generated by Django 4.2 on 2023-07-05 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0011_pageimage_articleimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="date",
            options={
                "ordering": ["-start_date", "-start_time"],
                "verbose_name": "date",
            },
        ),
    ]
