# Generated by Django 4.1.3 on 2022-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0012_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="docs/", verbose_name="Document"),
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
