# Generated by Django 4.1.3 on 2022-12-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0013_alter_document_file_delete_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                ("content", models.TextField(blank=True, verbose_name="Contenu")),
                (
                    "hidden",
                    models.BooleanField(default=False, verbose_name="Article caché"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
