# Generated by Django 4.1.3 on 2022-12-11 17:40

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0014_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspacecateUserVisit",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Time of the visit"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Django session identifier", max_length=40
                    ),
                ),
                (
                    "remote_addr",
                    models.CharField(
                        blank=True,
                        help_text="Client IP address (from X-Forwarded-For HTTP header, or REMOTE_ADDR request property)",
                        max_length=100,
                    ),
                ),
                (
                    "ua_string",
                    models.TextField(
                        blank=True,
                        help_text="Client User-Agent HTTP header",
                        verbose_name="User agent (raw)",
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        help_text="MD5 hash generated from request properties",
                        max_length=32,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True, help_text="View namespace", max_length=32
                    ),
                ),
                (
                    "view",
                    models.CharField(
                        blank=True, help_text="View name or object", max_length=32
                    ),
                ),
            ],
            options={
                "verbose_name": "Visite",
                "verbose_name_plural": "Visites",
                "get_latest_by": "timestamp",
                "abstract": False,
            },
        ),
    ]
