# Generated by Django 4.2 on 2023-07-07 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0014_alter_child_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"ordering": ["nom", "prenom"], "verbose_name": "child"},
        ),
    ]
