# Generated by Django 4.0.6 on 2022-12-19 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacecate', '0015_espacecateuservisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='annees_evf',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="Années d'éveil à la foi"),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='annees_kt',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Années de caté'),
        ),
    ]
