# Generated by Django 4.1.3 on 2022-12-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0016_alter_enfant_annees_evf_alter_enfant_annees_kt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Enfant",
            new_name="Child",
        ),
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name": "Enfant"},
        ),
    ]
