# Generated by Django 4.1.3 on 2022-12-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0017_rename_enfant_child_alter_child_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="espacecateuservisit",
            name="hash",
        ),
    ]
