# Generated by Django 4.1.3 on 2023-01-19 16:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import espacecate.models
import utils.fields


class Migration(migrations.Migration):

    replaces = [
        ("espacecate", "0020_rename_espacecateuservisit_uservisit_and_more"),
        ("espacecate", "0021_article_date"),
        ("espacecate", "0022_alter_article_options_alter_document_options_and_more"),
        ("espacecate", "0023_date"),
        ("espacecate", "0024_remove_date_date_date_end_date_date_start_date"),
        ("espacecate", "0025_alter_child_annee_pardon"),
        ("espacecate", "0026_alter_date_end_date_alter_date_time_text"),
        ("espacecate", "0027_alter_article_options"),
        ("espacecate", "0028_alter_document_file"),
    ]

    dependencies = [
        ("espacecate", "0019_espacecateuservisit_hash"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EspacecateUserVisit",
            new_name="UserVisit",
        ),
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 1, 1, 13, 7, 26, 878131, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "document"},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["order"], "verbose_name": "page"},
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden article"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="child",
            name="ecole",
            field=models.CharField(
                choices=[
                    ("FARANDOLE", "École La Farandole"),
                    ("SOLDANELLE", "École La Soldanelle"),
                    ("PASTEUR", "École Pasteur"),
                    ("CEZANNE", "École Cézanne"),
                    ("BARATIER", "École de Baratier"),
                    ("CHATEAUROUX", "École de Châteauroux"),
                    ("ST_ANDRE", "École de Saint-André"),
                    ("CROTS", "École de Crots"),
                    ("SAVINES", "École de Savines"),
                    ("ORRES", "École des Orres"),
                    ("PUYS", "École des Puys"),
                    ("MAISON", "École à la maison"),
                ],
                max_length=15,
                verbose_name="École",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="premiere_communion",
            field=models.BooleanField(verbose_name="Première communion"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Document title"),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden page"),
        ),
        migrations.AlterField(
            model_name="page",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="page",
            name="parent_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="espacecate.page",
                verbose_name="Previous page",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="child",
            name="annee_pardon",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1970),
                    django.core.validators.MaxValueValidator(
                        espacecate.models.get_current_year
                    ),
                ],
                verbose_name="Année du Sacrement du Pardon",
            ),
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(blank=True, verbose_name="Start time")),
                ("end_time", models.TimeField(blank=True, verbose_name="End time")),
                (
                    "time_text",
                    utils.fields.DatalistField(
                        blank=True, max_length=50, verbose_name="Time (as text)"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Short name"
                    ),
                ),
                ("place", models.CharField(max_length=100, verbose_name="Place")),
                ("cancelled", models.BooleanField(verbose_name="Cancelled")),
                ("end_date", models.DateField(blank=True, verbose_name="End date")),
                (
                    "start_date",
                    models.DateField(default="2023-01-02", verbose_name="Start date"),
                ),
            ],
            options={
                "verbose_name": "date",
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-date"], "verbose_name": "article"},
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(null=True, upload_to="", verbose_name="File"),
        ),
    ]
