# Generated by Django 4.2.3 on 2023-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0019_alter_child_classe_alter_child_ecole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="lieu_bapteme",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Lieu du Baptême"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="child",
            name="lieu_premiere_communion",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Lieu de la Première Communion",
            ),
            preserve_default=False,
        ),
    ]
