# Generated by Django 4.2.3 on 2023-08-27 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("espacecate", "0020_alter_child_lieu_bapteme_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="date_item",
        ),
    ]
