# Generated by Django 4.1.3 on 2023-01-02 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ("filer", "0015_alter_file_owner_alter_file_polymorphic_ctype_and_more"),
        ("espacecate", "0021_article_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "article"},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "document"},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["order"], "verbose_name": "page"},
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden article"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="child",
            name="ecole",
            field=models.CharField(
                choices=[
                    ("FARANDOLE", "École La Farandole"),
                    ("SOLDANELLE", "École La Soldanelle"),
                    ("PASTEUR", "École Pasteur"),
                    ("CEZANNE", "École Cézanne"),
                    ("BARATIER", "École de Baratier"),
                    ("CHATEAUROUX", "École de Châteauroux"),
                    ("ST_ANDRE", "École de Saint-André"),
                    ("CROTS", "École de Crots"),
                    ("SAVINES", "École de Savines"),
                    ("ORRES", "École des Orres"),
                    ("PUYS", "École des Puys"),
                    ("MAISON", "École à la maison"),
                ],
                max_length=15,
                verbose_name="École",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="premiere_communion",
            field=models.BooleanField(verbose_name="Première communion"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=filer.fields.file.FilerFileField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="filer.file",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Document title"),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden page"),
        ),
        migrations.AlterField(
            model_name="page",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="page",
            name="parent_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="espacecate.page",
                verbose_name="Previous page",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
    ]
