# Generated by Django 4.1.3 on 2023-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0022_alter_article_options_alter_document_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(blank=True, verbose_name="Start time")),
                ("end_time", models.TimeField(blank=True, verbose_name="End time")),
                (
                    "time_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Time (as text)"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Short name"
                    ),
                ),
                ("place", models.CharField(max_length=100, verbose_name="Place")),
                ("cancelled", models.BooleanField(verbose_name="Cancelled")),
            ],
            options={
                "verbose_name": "date",
                "abstract": False,
            },
        ),
    ]
