# Generated by Django 4.1.3 on 2023-01-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0023_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="date",
            name="date",
        ),
        migrations.AddField(
            model_name="date",
            name="end_date",
            field=models.DateField(default="2023-01-02", verbose_name="End date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="date",
            name="start_date",
            field=models.DateField(default="2023-01-02", verbose_name="Start date"),
            preserve_default=False,
        ),
    ]
