# Generated by Django 4.1.3 on 2023-01-03 15:41

import django.core.validators
from django.db import migrations, models
import espacecate.models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0024_remove_date_date_date_end_date_date_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="annee_pardon",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1970),
                    django.core.validators.MaxValueValidator(
                        espacecate.models.get_current_year
                    ),
                ],
                verbose_name="Année du Sacrement du Pardon",
            ),
        ),
    ]
