# Generated by Django 4.1.3 on 2023-01-08 08:13

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0025_alter_child_annee_pardon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="end_date",
            field=models.DateField(blank=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="date",
            name="time_text",
            field=utils.fields.DatalistField(
                blank=True, max_length=50, verbose_name="Time (as text)"
            ),
        ),
    ]
