# Generated by Django 4.1.3 on 2023-01-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0026_alter_date_end_date_alter_date_time_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-date"], "verbose_name": "article"},
        ),
    ]
