# Generated by Django 4.1.3 on 2023-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0027_alter_article_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(null=True, upload_to="", verbose_name="File"),
        ),
    ]
