# Generated by Django 4.1.3 on 2023-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "espacecate",
            "0020_rename_espacecateuservisit_uservisit_and_more_squashed_0028_alter_document_file",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="start_date",
            field=models.DateField(verbose_name="Start date"),
        ),
    ]
