# Generated by Django 4.1.3 on 2023-01-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filer", "0015_alter_file_owner_alter_file_polymorphic_ctype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("_height", models.FloatField(blank=True, null=True)),
                ("_width", models.FloatField(blank=True, null=True)),
                (
                    "default_alt_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="default alt text",
                    ),
                ),
                (
                    "default_caption",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="default caption",
                    ),
                ),
                (
                    "subject_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="subject location",
                    ),
                ),
                (
                    "file_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s_file",
                        serialize=False,
                        to="filer.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("filer.file",),
        ),
    ]
