# Generated by Django 5.0.6 on 2024-10-09 10:18

import django.db.models.deletion
import storage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.IntegerField(unique=True, verbose_name="jour")),
                ("child", models.CharField(max_length=100, verbose_name="enfant")),
                ("picture", storage.fields.ImageField(blank=True, null=True, upload_to="", verbose_name="photo")),
                ("holiday", models.CharField(max_length=100, verbose_name="fête")),
                ("content", models.TextField(blank=True, verbose_name="contenu")),
            ],
            options={
                "verbose_name": "Jour",
            },
        ),
        migrations.CreateModel(
            name="DayImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", storage.fields.ImageField(upload_to="", verbose_name="image")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="calendrier_avent_2024.day", verbose_name="Day"
                    ),
                ),
            ],
            options={
                "verbose_name": "day image",
                "verbose_name_plural": "day images",
            },
        ),
    ]
