# Generated by Django 5.1.2 on 2024-11-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendrier_avent_2024", "0001_initial"),
        ("espacecate", "0002_alter_page_parent_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="picture",
        ),
        migrations.AlterField(
            model_name="day",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="espacecate.child", verbose_name="enfant"
            ),
        ),
    ]
