# Generated by Django 4.2.11 on 2024-11-14 17:45

from django.db import migrations, models


def add_children_name(apps, _schema_editor):
    Day = apps.get_model("calendrier_avent_2024", "Day")
    Child = apps.get_model("espacecate", "Child")
    for day in Day.objects.all():
        try:
            child_id = int(day.child_or_animator)
        except ValueError:
            pass
        else:
            day.child_or_animator = Child.objects.get(pk=child_id).prenom
            day.save()


def remove_children_name(apps, _schema_editor):
    Day = apps.get_model("calendrier_avent_2024", "Day")
    Child = apps.get_model("espacecate", "Child")
    for day in Day.objects.all():
        try:
            day.child_or_animator = Child.objects.get(prenom__istartswith=day.child_or_animator).pk
        except (Child.DoesNotExist, Child.MultipleObjectsReturned):
            pass
        else:
            day.save()


class Migration(migrations.Migration):

    dependencies = [
        ("calendrier_avent_2024", "0002_remove_day_picture_alter_day_child"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="child",
            field=models.CharField(max_length=100, verbose_name="enfant"),
        ),
        migrations.RenameField(
            model_name="day",
            old_name="child",
            new_name="child_or_animator",
        ),
        migrations.RunPython(add_children_name, remove_children_name),
    ]
