# Generated by Django 4.2.11 on 2024-11-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendrier_avent_2024", "0003_alter_day_child"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="child_or_animator",
            field=models.CharField(max_length=100, verbose_name="enfant ou animateur"),
        ),
    ]
