# Generated by Django 4.1.3 on 2022-12-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0002_rename_titre_page_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="espacecate.page",
                    ),
                ),
            ],
            bases=("espacecate.page",),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="page",
            name="id",
            field=models.SlugField(
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titre"),
        ),
    ]
