# Generated by Django 5.1.4 on 2024-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0004_simplify_child_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="communion_cette_annee",
            field=models.BooleanField(default=False, verbose_name="Communion cette année"),
        ),
    ]
