# Generated by Django 5.1.4 on 2024-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0005_add_default_false"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="classe",
            field=models.TextField(
                choices=[
                    ("PS", "Petite section"),
                    ("MS", "Moyenne section"),
                    ("GS", "Grande section"),
                    ("CP", "CP"),
                    ("CE1", "CE1"),
                    ("CE2", "CE2"),
                    ("CM1", "CM1"),
                    ("CM2", "CM2"),
                    ("autre", "Autre"),
                ],
                max_length=5,
                verbose_name="Classe",
            ),
        ),
    ]
