# Generated by Django 4.1.3 on 2022-12-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0006_rename_address_child_adresse_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="child",
            old_name="years_evf",
            new_name="annees_evf",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="years_kt",
            new_name="annees_kt",
        ),
    ]
