# Generated by Django 4.1.3 on 2022-12-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0009_page_hidden_page_parent_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
