# Generated by Django 5.2.4 on 2025-07-29 08:52

from django.db import migrations, models

from common.migration_helpers import migrate_paye_backwards, migrate_paye_forwards


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0009_delete_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="paye_checkbox",
            field=models.BooleanField(default=False, verbose_name="Payé"),
        ),
        migrations.RunPython(migrate_paye_forwards("espacecate"), migrate_paye_backwards("espacecate")),
        migrations.RemoveField(
            model_name="child",
            name="paye",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="paye_checkbox",
            new_name="paye",
        ),
    ]
