# Generated by Django 4.1.3 on 2022-12-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0010_alter_page_options_page_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Titre du document"),
                ),
                ("file", models.FileField(upload_to="", verbose_name="Document")),
            ],
        ),
        migrations.AlterField(
            model_name="page",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="page",
            name="parent_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="espacecate.page",
                verbose_name="Page précédente",
            ),
        ),
    ]
