# Generated by Django 5.2.4 on 2025-07-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("espacecate", "0011_remove_articleimage_page_remove_attendance_child_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name": "child", "verbose_name_plural": "children"},
        ),
    ]
